spring.application.name=mercadoexpress

server.port=8082

# Conexao com o Oracle FIAP

spring.datasource.url=jdbc:oracle:thin:@${DB_HOST:oracle.fiap.com.br}:${DB_PORT:1521}:${DB_SERVICE:orcl}
spring.datasource.username=${DB_USER:SEU_RM_AQUI}
spring.datasource.password=${DB_PASSWORD:SUA_SENHA_AQUI}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
